Table "test_table" {
  "id" int [pk, not null, increment]
  "column1" varchar(255) [default: null]
  "column2" varchar(255) [default: null]
  "column3" varchar(255) [default: null]
  "column4" varchar(255) [default: null]
  "column5" varchar(255) [default: null]
  "column6" varchar(255) [default: null]
  "column7" varchar(255) [default: null]
  "column8" varchar(255) [default: null]
  "column9" varchar(255) [default: null]
  "column10" varchar(255) [default: null]
  "column11" varchar(255) [default: null]
  "column12" varchar(255) [default: null]
  "column13" varchar(255) [default: null]
  "column14" varchar(255) [default: null]
  "column15" varchar(255) [default: null]
  "column16" varchar(255) [default: null]
  "column17" varchar(255) [default: null]
  "column18" varchar(255) [default: null]
  "column19" varchar(255) [default: null]
  "column20" varchar(255) [default: null]
  "column100" varchar(255) [default: null]
}
