Enum "clientes_raca_enum" {
  "branca"
  "preta"
  "parda"
  "indígena"
  "amarela"
}

Enum "vendas_modo_de_pagamento_enum" {
  "boleto"
  "pix"
  "transferencia"
  "cartao_de_credito"
  "cartao_de_debito"
}

Table "clientes" {
  "id" int [pk, not null, increment]
  "id_endereco_primario" int [not null]
  "id_endereco_secundario" int [default: null]
  "foto" blob
  "nome" varchar(255) [not null]
  "sobrenome" varchar(255) [not null]
  "nome_social" varchar(255) [default: null]
  "genero" varchar(255) [default: null]
  "estado_civil" varchar(255) [default: null]
  "profissao" varchar(255) [default: null]
  "razao_social_empresa" varchar(255) [default: null]
  "cnpj" int [default: null]
  "data_de_nascimento" date [not null]
  "nacionalidade" varchar(255) [default: null]
  "raca" clientes_raca_enum [default: null]
  "cpf" int [not null]
  "data_de_emissao" date [not null]
  "orgao_expedidor" varchar(255) [not null]
  "numero_do_cartao_bancario" int [default: null]
  "validade_do_cartao_bancario" date [default: null]
  "cvv" int [default: null]
  "credito" tinyint(1) [default: null]
  "telefone_primario" int [not null]
  "telefone_secundario" int [default: null]
  "e_mail" varchar(255) [default: null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "enderecos" {
  "id" int [pk, not null, increment]
  "id_cliente" int [not null]
  "rua" varchar(255) [not null]
  "numero" varchar(255) [not null]
  "complemento" varchar(255) [default: null]
  "bairro" varchar(255) [not null]
  "cidade" varchar(255) [not null]
  "estado" varchar(255) [not null]
  "pais" varchar(255) [not null]
  "cep" int [not null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "fotos" {
  "id" int [pk, not null, increment]
  "id_produto" int [not null]
  "foto" blob [not null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "links_externos" {
  "id" int [pk, not null, increment]
  "id_produto" int [not null]
  "link_externo" varchar(255) [not null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "manuais" {
  "id" int [pk, not null, increment]
  "id_produto" int [not null]
  "manual" blob [not null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "pedidos" {
  "id" int [pk, not null, increment]
  "id_venda" int [not null]
  "id_produto" int [not null]
  "quantidade" int [not null]
  "desconto" double [default: null]

  Indexes {
    id [unique, name: "id"]
    id_venda [name: "id_venda"]
    id_produto [name: "id_produto"]
  }
}

Table "precos" {
  "id" int [pk, not null, increment]
  "id_produto" int [not null]
  "preco" double [not null]
  "data_hora_de_inicio" datetime [not null]
  "data_hora_de_termino" datetime [default: null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "produtos" {
  "id" int [pk, not null, increment]
  "id_subtipo" int [not null]
  "estoque" int [not null]
  "peso" double [not null]
  "tamanho_da_caixa_x" double [not null]
  "tamanho_da_caixa_y" double [not null]
  "tamanho_da_caixa_z" double [not null]
  "maximo_de_caixas_empilhadas" int [not null]
  "fragil" tinyint(1) [not null]
  "perigoso" tinyint(1) [not null]
  "validade" datetime [not null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "subtipos" {
  "id" int [pk, not null, increment]
  "id_tipo" int [not null]
  "subtipo" varchar(255) [not null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "tipos" {
  "id" int [pk, not null, increment]
  "tipo" varchar(255) [not null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "vendas" {
  "id" int [pk, not null, increment]
  "id_cliente" int [not null]
  "id_endereco" int [not null]
  "modo_de_pagamento" vendas_modo_de_pagamento_enum [default: null]
  "quantidade_de_parcelas" int [not null]
  "juros" double [default: null]
  "dia_de_vencimento" int [default: null]
  "data_do_primeiro_vencimento" date [not null]
  "data_hora_da_venda" datetime [not null]
  "data_hora_de_entrega" datetime [not null]
  "condicoes" text
  "nota_fiscal" blob [not null]

  Indexes {
    id [unique, name: "id"]
    id_cliente [name: "id_cliente"]
    id_endereco [name: "id_endereco"]
  }
}

Table "videos" {
  "id" int [pk, not null, increment]
  "id_produto" int [not null]
  "video" blob [not null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "volume_vendas_diario" {
  "id" int [pk, not null, increment]
  "quantidade" int [not null]
  "dia" date [default: null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "volume_vendas_diario_estadual" {
  "id" int [pk, not null, increment]
  "quantidade" int [not null]
  "dia" date [default: null]
  "estado" varchar(255) [default: null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "volume_vendas_diario_municipal" {
  "id" int [pk, not null, increment]
  "quantidade" int [not null]
  "dia" date [default: null]
  "municipio" varchar(255) [default: null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "volume_vendas_mensal" {
  "id" int [pk, not null, increment]
  "quantidade" int [not null]
  "mes" int [default: null]
  "ano" int [default: null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "volume_vendas_mensal_estadual" {
  "id" int [pk, not null, increment]
  "quantidade" int [not null]
  "mes" int [default: null]
  "ano" int [default: null]
  "estado" varchar(255) [default: null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "volume_vendas_mensal_municipal" {
  "id" int [pk, not null, increment]
  "quantidade" int [not null]
  "mes" int [default: null]
  "ano" int [default: null]
  "municipio" varchar(255) [default: null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "volume_vendas_semanal" {
  "id" int [pk, not null, increment]
  "quantidade" int [not null]
  "semana" int [default: null]
  "ano" int [default: null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "volume_vendas_semanal_estadual" {
  "id" int [pk, not null, increment]
  "quantidade" int [not null]
  "semana" int [default: null]
  "ano" int [default: null]
  "estado" varchar(255) [default: null]

  Indexes {
    id [unique, name: "id"]
  }
}

Table "volume_vendas_semanal_municipal" {
  "id" int [pk, not null, increment]
  "quantidade" int [not null]
  "semana" int [default: null]
  "ano" int [default: null]
  "municipio" varchar(255) [default: null]

  Indexes {
    id [unique, name: "id"]
  }
}

Ref "pedidos_ibfk_1":"vendas"."id" < "pedidos"."id_venda"

Ref "pedidos_ibfk_2":"produtos"."id" < "pedidos"."id_produto"

Ref "vendas_ibfk_1":"clientes"."id" < "vendas"."id_cliente"

Ref "vendas_ibfk_2":"enderecos"."id" < "vendas"."id_endereco"
